### ISSUE TITLE
[improvement] Remove left overs from CCB

### ISSUE THREAD

**Issue by kumpera** [VowpalWabbit/reinforcement_learning#142]
As CCB designed evolved, some bits turned out be to redundant and we slipped from removing them.
They should be removed from the code base.

In no particular order:
- We don't need a separate decision sender
https://github.com/VowpalWabbit/reinforcement_learning/blob/master/rlclientlib/live_model_impl.cc#L281

- We don't need to register a new sender type (it's identical to existing sender types):
https://github.com/VowpalWabbit/reinforcement_learning/blob/master/rlclientlib/azure_factories.cc#L22

**Comment by prateekiiest** [comment]
Hey @kumpera. This seems a good first issue. Is anyone working on this at the moment?
