### ISSUE TITLE
Python documentation

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/reinforcement_learning#150]
Current Python documentation is generated using doxygen and doesn't seem to really outline the Python API. We should instead use autodoc with Sphinx or something similar.

**Comment by Yash621** [comment]
hey !! I am interested in doing this ,Can you guide me through this ? As I am new to this !!
Thank you.

**Comment by jackgerrits** [comment]
This issue is actually already complete. The autogenerated docs can be found here https://vowpalwabbit.org/docs/reinforcement_learning/python/latest/
