### ISSUE TITLE
Get rid of copy paste in loggers initialization

### ISSUE THREAD

**Issue by ataymano** [VowpalWabbit/reinforcement_learning#172]
Right now we have several sets of parameters required for logger initialization in a single plain list:
"interaction.eventhub.host",
"interaction.eventhub.name",
"interaction.eventhub.keyname",
...
"observation.eventhub.host",
"observation.eventhub.name",
"observation.eventhub.keyname",
...
It introduces some amount of copy-paste for all logger implementations.
It would be helpful either to move to more structured config:
"interaction_config": {"eventhub" { "host", "name"}},...
or at least simulate this behavior by accessing to certain keys of config by prefix

**Comment by kumpera** [comment]
This issue was fixed by #210.
