### ISSUE TITLE
Move serialization to background thread

### ISSUE THREAD

**Issue by kumpera** [VowpalWabbit/reinforcement_learning#221]
Schema v2 led serialization to happen on the main thread, which has two undesirable consequences.
First, it moves work to application threads and that will increase the latency of each decision - this might be particularly bad in the case of dedup+compression.
Second, it disables any single threaded optimizations that require shared state across serialization calls. We can't reuse the compression context across serialization calls due to it.

**Comment by peterychang** [comment]
Closed with https://github.com/VowpalWabbit/reinforcement_learning/pull/438
