### ISSUE TITLE
[binary-log] Implement activation logic.

### ISSUE THREAD

**Issue by kumpera** [VowpalWabbit/reinforcement_learning#298]
A decision can use the `deferred_action` field to signal that the agent might not take its action.

When that field is `true`, the agent must send an observation with `action_taken = true` to signal that the action was... taken.

The trainer must check for those two fields to decided whether it should learn on a joined decision or not. The logic for that is the following:

```
should_learn: !decision.deferred_action || (decision.deferred_action && observations.at_least_one(o => o.action_taken))
```

**Comment by olgavrou** [comment]
this has been implemented in the binary parser for cb/ccb so closing as we track this for every parsing type we implement
