### ISSUE TITLE
Add test for CCB no model exploration

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/reinforcement_learning#93]
It seems to be doing the incorrect thing in C# currently. Two 0 actions were witnessed

**Comment by lokitoth** [comment]
[DebugRLNuget.zip](https://github.com/VowpalWabbit/reinforcement_learning/files/3443933/DebugRLNuget.zip)

Simple repro case where lack of model traps us in explore mode, returns action id = 0 for both slots.

**Comment by jackgerrits** [comment]
Looking at the repro, it looks like the model was started with the incorrect VW command line, `cb_explore_adf` but it should be `ccb_explore_adf`, but there is also more in the command line which handles model free exploration. In this case the default command line should be used.

Regardless, I just fixed a few bugs that may have still impacted this. I've added a test to verify model free exploration.

51ba555e883bfdccc5117716771be9c6f5cf9b60
